// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerManager.Server.Context;

#nullable disable

namespace PowerManager.Server.Context.Migrations
{
    [DbContext(typeof(PowerManagerContext))]
    [Migration("20260722093929_ElectricPower Add")]
    partial class ElectricPowerAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PowerManager.Server.Context.Entity.Device", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardConnector")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double?>("VoltCalibration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("ID");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("PowerManager.Server.Context.Entity.ElectricPower", b =>
                {
                    b.Property<string>("PowerType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PowerType");

                    b.ToTable("ElectricPower");

                    b.HasData(
                        new
                        {
                            PowerType = "HouseLow",
                            PowerTypeName = "주택용 저압"
                        },
                        new
                        {
                            PowerType = "HouseHigh",
                            PowerTypeName = "주택용 고압"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
